# Generated by Django 3.2.4 on 2021-09-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='ipGW',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ipmasque',
        ),
    ]
