# Generated by Django 3.2.4 on 2021-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0004_service_ipadresspublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
