# Generated by Django 3.2.4 on 2021-09-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0007_delservice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='script',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='script',
            name='task',
        ),
    ]
