# Generated by Django 3.2.4 on 2021-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0008_auto_20210915_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='list_adresse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
