# Generated by Django 3.2.4 on 2021-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0009_service_list_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listadresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_adresse', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='list_adresse',
        ),
    ]
