# Generated by Django 3.2.4 on 2021-09-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0010_auto_20210917_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listadresse',
        ),
    ]
