# Generated by Django 3.2.4 on 2021-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0011_delete_listadresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ipadresspublic31',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
