# Generated by Django 3.2.4 on 2021-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0012_service_ipadresspublic31'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nbraddpriv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='nbraddpub31',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='nbraddpub32',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
