# Generated by Django 3.2.4 on 2021-09-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0014_auto_20210918_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='routeur',
        ),
    ]
