# Generated by Django 3.2.4 on 2021-09-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0015_remove_execution_routeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vc',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list_routeurs.switch', to_field='namedevice'),
        ),
    ]
