# Generated by Django 3.2.4 on 2021-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0018_auto_20210925_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
