# Generated by Django 3.2.4 on 2021-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0019_alter_script_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='debit',
            field=models.PositiveIntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='interface',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='vlan',
            field=models.PositiveIntegerField(max_length=5, null=True),
        ),
    ]
