# Generated by Django 3.2.4 on 2021-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0020_auto_20210926_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='debit',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='interface',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='vlan',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
