# Generated by Django 3.2.4 on 2021-09-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0021_auto_20210926_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
