# Generated by Django 3.2.4 on 2021-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0023_remove_script_vlan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delservice',
            name='vlan',
        ),
        migrations.AlterField(
            model_name='delservice',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
