# Generated by Django 3.2.4 on 2021-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0024_auto_20210926_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100, null=True)),
                ('List_client', models.CharField(blank=True, choices=[], max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
