# Generated by Django 3.2.4 on 2021-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0025_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2vc',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
