# Generated by Django 3.2.4 on 2021-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0026_auto_20211004_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='switch',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
