# Generated by Django 3.2.4 on 2021-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0029_trafic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafic',
            name='trafic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
