# Generated by Django 3.2.4 on 2021-10-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0030_alter_trafic_trafic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafic',
            old_name='trafic',
            new_name='percent',
        ),
    ]
