# Generated by Django 3.2.4 on 2021-10-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0031_rename_trafic_trafic_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafic',
            name='percent',
            field=models.IntegerField(blank=True, choices=[], null=True),
        ),
        migrations.AlterField(
            model_name='trafic',
            name='routeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='list_routeurs.routeur', to_field='Loopback'),
        ),
    ]
