# Generated by Django 3.2.4 on 2021-10-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0032_auto_20211006_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafic',
            name='routeur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
