# Generated by Django 3.2.4 on 2021-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0035_dimens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimens',
            name='liaison',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
