# Generated by Django 3.2.4 on 2021-10-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0036_alter_dimens_liaison'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimens',
            name='capa',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
