# Generated by Django 3.2.4 on 2021-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0037_dimens_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimens',
            name='type',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
