# Generated by Django 3.2.4 on 2021-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0040_dimens_loopback_dim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bh_sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liaison', models.CharField(max_length=20000, null=True)),
                ('loopback_dim', models.CharField(max_length=20000, null=True)),
                ('percent', models.FloatField(blank=True, default=0, null=True)),
                ('interface', models.CharField(max_length=20000, null=True)),
                ('capa', models.CharField(max_length=20000, null=True)),
                ('typeBH', models.CharField(choices=[('BH_TT', 'BH_TT'), ('BH_OOO', 'BH_OOO')], max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
