# Generated by Django 3.2.4 on 2021-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0041_bh_sharing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20000, null=True)),
                ('interface', models.CharField(max_length=20000, null=True)),
                ('percent', models.FloatField(blank=True, default=0, null=True)),
                ('capa', models.CharField(max_length=20000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
