# Generated by Django 3.2.4 on 2021-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0042_fn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fn',
            name='routeur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
