# Generated by Django 3.2.4 on 2021-10-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0043_fn_routeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vc',
            name='generate',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
