# Generated by Django 3.2.4 on 2021-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0044_l2vc_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='delservice',
            name='generate',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='generate',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='generate',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
