# Generated by Django 3.2.4 on 2021-10-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0045_auto_20211016_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
