# Generated by Django 3.2.4 on 2021-10-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0046_switch_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='capa',
            field=models.CharField(default='1G', max_length=20000, null=True),
        ),
    ]
