# Generated by Django 3.2.4 on 2021-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0048_dimens_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeur',
            name='percentcpu',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='routeur',
            name='percentmemory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
