# Generated by Django 3.2.4 on 2021-11-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0049_auto_20211106_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(default='nom du client', max_length=100, null=True)),
                ('interface', models.CharField(default='exp:0/0/0', max_length=100, null=True)),
                ('vlan', models.PositiveIntegerField(max_length=5, null=True)),
                ('debit', models.PositiveIntegerField(blank=True, max_length=5, null=True)),
                ('ipGW', models.CharField(max_length=100, null=True)),
                ('ipmasque', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('VRF', models.CharField(choices=[('Internet_vpn', 'Internet_vpn'), ('Voice_vpn', 'Voice_vpn'), ('CCTV_Wimax', 'CCTV_Wimax'), ('MonitoringB2B_vpn', 'MonitoringB2B_vpn')], max_length=100, null=True)),
                ('trans', models.CharField(choices=[('FH', 'FH'), ('FO', 'FO')], max_length=100, null=True)),
                ('routeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='list_routeurs.routeur', to_field='Loopback')),
            ],
        ),
    ]
