# Generated by Django 3.2.4 on 2021-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0052_alter_servicemanuel_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemanuel',
            name='interface',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
