# Generated by Django 3.2.4 on 2021-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0055_alter_servicemanuel_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanuel',
            name='dist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemanuel',
            name='dist1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemanuel',
            name='ipmasquedis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemanuel',
            name='ipmasquedis1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemanuel',
            name='nexthopedis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemanuel',
            name='nexthopedis1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
