# Generated by Django 3.2.4 on 2021-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0056_auto_20211117_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanuel',
            name='switch',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicemanuel',
            name='interface',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
