# Generated by Django 3.2.4 on 2021-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0057_auto_20211119_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanuel',
            name='interfacertsw',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
