# Generated by Django 3.2.4 on 2021-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0058_servicemanuel_interfacertsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='interfacertsw',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
