# Generated by Django 3.2.4 on 2021-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0062_alter_service_vrf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='VRF',
            field=models.CharField(choices=[('Internet_vpn', 'Internet_vpn')], max_length=100, null=True),
        ),
    ]
