# Generated by Django 3.2.9 on 2021-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0063_alter_service_vrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_name', models.CharField(blank=True, max_length=20000000, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=20000000, null=True)),
                ('source', models.CharField(blank=True, max_length=20000000, null=True)),
                ('target', models.CharField(blank=True, max_length=20000000, null=True)),
                ('srcUtilMap', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_node', models.CharField(blank=True, max_length=20000000, null=True)),
                ('name', models.CharField(blank=True, max_length=20000000, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20000000, null=True)),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
