# Generated by Django 3.2.9 on 2022-02-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0065_alter_servicemanuel_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='date_changement',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='etat',
            field=models.CharField(blank=True, default='DEMANDE', max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='swan',
            field=models.CharField(blank=True, default='XXXXX', max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='usersupport',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='date_changement',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='etat',
            field=models.CharField(blank=True, default='DEMANDE', max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='swan',
            field=models.CharField(blank=True, default='XXXXX', max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='usersupport',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
