# Generated by Django 3.2.9 on 2022-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0066_auto_20220208_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='range_adress',
            field=models.CharField(choices=[('FH', 'FH'), ('FO', 'FO')], max_length=100, null=True),
        ),
    ]
