# Generated by Django 3.2.9 on 2022-02-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0068_remove_service_range_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ipadresspublic28',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='ipadresspublic29',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
