# Generated by Django 3.2.9 on 2022-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0069_auto_20220219_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
