# Generated by Django 3.2.9 on 2022-02-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0070_auto_20220220_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
