# Generated by Django 3.2.9 on 2022-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0071_alter_service_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
