# Generated by Django 3.2.9 on 2022-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0072_alter_script_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
