# Generated by Django 3.2.9 on 2022-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0073_auto_20220220_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='usersupport',
        ),
        migrations.RemoveField(
            model_name='service',
            name='usersupport',
        ),
        migrations.AlterField(
            model_name='script',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='date_changement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_changement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
