# Generated by Django 3.2.9 on 2022-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0074_auto_20220224_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='interfacertsw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='switch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
