# Generated by Django 3.2.9 on 2022-02-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0076_historicalservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalService',
        ),
    ]
