# Generated by Django 3.2.9 on 2022-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0079_historicalscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscript',
            name='generate',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='generate',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='generate',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='generate',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
