# Generated by Django 3.2.9 on 2022-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0080_auto_20220307_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='ipadress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ipadress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
