# Generated by Django 3.2.9 on 2022-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0081_auto_20220307_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingB2BService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(blank=True, max_length=20000000, null=True)),
                ('nbr_service_Internet', models.PositiveIntegerField(blank=True, null=True)),
                ('nbr_service_voip', models.PositiveIntegerField(blank=True, null=True)),
                ('nbr_service_L2VC', models.PositiveIntegerField(blank=True, null=True)),
                ('nbr_service_BUSINESS_CLIENT_VSI', models.PositiveIntegerField(blank=True, null=True)),
                ('nbr_service_BUSINESS_VSI', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
