# Generated by Django 3.2.9 on 2022-03-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_routeurs', '0082_reportingb2bservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingb2bservice',
            old_name='name_service',
            new_name='name_device',
        ),
    ]
